version: '3.4'

services:
  scaautenticacao:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"

  scagateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10000:80"


  scacompliance:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  scaapresentacao:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
      #- "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  scaativos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  scainteligencianegocio:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  scamonitoramento:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  scaprocessominerario:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  scaseguranca:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

